spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.kikianju.codeChecker.reviewSystem

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
